In this notebook, I want mainly want to try to feature engineer up to degree two and see if interactions between stats have any more predictive power. The thing is, this level of dimensionality (around 3000 features) will cause extreme overfitting of the data in a non-regularized logistic regressor, but forward feature selection to select features is difficult due to extreme computational requirements when the degree gets that high. So, I will try to use lasso regression to do implicit feature selection on this higher dimension dataset to try to reduce some dimensionality more feasibly. I will not go beyond degree two since degree three already jumps from ~3000 features to ~79000 features which is computationally infeasible.

In [2]:
import pandas as pd
df = pd.read_csv("../../data/aggregated_rolling_features.csv")
df.shape

(5539, 97)

In [3]:
to_drop = []
to_drop.extend([f"team{i}_player{k}_id" for i in range(1,3) for k in range(1,6)])
to_drop.extend([f"team{i}_id" for i in range(1,3)])
to_drop.extend([f"team{i}" for i in range(1,3)])
to_drop.extend(["tournament", "match_id", "game_id", "map_id", "map_name", "datetime", "Unnamed: 0"])
df = df.drop(to_drop, axis=1)
df

,team1_win,bestOf,team1_previous_10_average_map_score,team2_previous_10_average_map_score,previous_10_games_team1_average_kills,previous_10_games_team1_std_kills,previous_10_games_team1_range_kills,previous_10_games_team1_max_kills,previous_10_games_team1_min_kills,previous_10_games_team1_median_kills,...,previous_10_games_team2_range_kast,previous_10_games_team2_max_kast,previous_10_games_team2_min_kast,previous_10_games_team2_median_kast,previous_10_games_team2_average_kddiff,previous_10_games_team2_std_kddiff,previous_10_games_team2_range_kddiff,previous_10_games_team2_max_kddiff,previous_10_games_team2_min_kddiff,previous_10_games_team2_median_kddiff
0,0,3.0,13.000000,13.000000,16.000000,0.000000e+00,0.0,16.000000,16.000000,16.000000,...,0.00,70.000000,70.000000,70.000000,1.000000,0.000000,0.0,1.000000,1.000000,1.000000
1,1,3.0,12.333333,12.333333,15.600000,4.127953e+00,10.0,22.000000,12.000000,13.000000,...,25.00,83.300000,58.300000,58.300000,-0.600000,3.136877,9.0,4.000000,-5.000000,0.000000
2,1,3.0,11.600000,11.600000,15.100000,2.083267e+00,5.5,18.500000,13.000000,14.000000,...,17.30,75.000000,57.700000,60.100000,-1.600000,5.885576,17.5,8.500000,-9.000000,-1.500000
3,1,3.0,11.571429,11.571429,14.612903,1.776357e-15,0.0,14.612903,14.612903,14.612903,...,0.00,71.535484,71.535484,71.535484,-0.032258,0.000000,0.0,-0.032258,-0.032258,-0.032258
4,1,3.0,10.666667,10.666667,13.600000,4.363485e+00,13.0,21.000000,8.000000,13.000000,...,33.30,60.000000,26.700000,33.300000,-9.000000,2.280351,6.0,-6.000000,-12.000000,-9.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5534,0,3.0,13.400000,9.500000,14.140000,9.200000e-01,2.6,15.400000,12.800000,14.200000,...,6.89,77.400000,70.510000,76.760000,0.780000,2.465279,6.4,3.500000,-2.900000,1.800000
5535,0,3.0,9.700000,11.100000,14.680000,1.175415e+00,3.3,16.600000,13.300000,14.900000,...,6.96,78.300000,71.340000,76.820000,0.920000,2.741095,7.0,3.700000,-3.300000,2.300000
5536,1,3.0,11.000000,10.700000,14.440000,6.590903e-01,1.7,15.400000,13.700000,14.600000,...,6.96,79.800000,72.840000,75.820000,1.140000,2.793278,7.1,3.900000,-3.200000,2.700000
5537,0,5.0,11.400000,12.700000,14.780000,2.594147e+00,6.8,17.500000,10.700000,14.900000,...,5.71,83.730000,78.020000,82.000000,4.280000,3.398470,8.7,7.800000,-0.900000,5.200000
5538,0,5.0,10.700000,13.300000,14.560000,2.427839e+00,6.6,17.700000,11.100000,14.700000,...,6.27,84.290000,78.020000,82.430000,4.420000,3.263372,8.9,8.000000,-0.900000,5.600000

In [4]:
X = df.drop("team1_win", axis=1)
y = df.team1_win

In [5]:
X_numerical = X.drop("bestOf", axis=1)
X_categorical = X.bestOf
X_categorical = pd.get_dummies(X_categorical, drop_first=True,dtype=int,prefix="bestOf")

Let's get the feature engineered set before standardizing

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2,include_bias=False)
X_numerical_poly_prime = poly.fit_transform(X_numerical)
X_numerical_poly = pd.DataFrame(X_numerical_poly_prime, columns=poly.get_feature_names_out(X_numerical.columns))
X_poly = pd.concat([X_numerical_poly, X_categorical], axis=1)
X_poly.shape

(5539, 2851)

Standardize

In [7]:
from sklearn.preprocessing import StandardScaler
from math import ceil
stnd = StandardScaler().set_output(transform="pandas")
#Split
split_point = ceil(len(df) * 0.8)
train_numerical = X_numerical.iloc[:split_point] # 0 to split_point - 1
test_numerical = X_numerical.iloc[split_point:] # split_point to len(df)
train_poly = X_poly.iloc[:split_point] # 0 to split_point - 1
test_poly = X_poly.iloc[split_point:] # split_point to len(df)
train_cat = X_categorical.iloc[:split_point]
test_cat = X_categorical.iloc[split_point:]
y_train = y.iloc[:split_point]
y_test = y.iloc[split_point:]
#Standardize
train_numerical = stnd.fit_transform(train_numerical)
test_numerical = stnd.transform(test_numerical)
train_poly = stnd.fit_transform(train_poly)
test_poly = stnd.transform(test_poly)
#Concat
X_train = pd.concat([train_numerical, train_cat], axis=1)
X_test = pd.concat([test_numerical, test_cat], axis=1)
X_poly_train = pd.concat([train_poly, train_cat], axis=1)
X_poly_test = pd.concat([test_poly, test_cat], axis=1)
#Show results
print("X_train shape", X_train.shape)
print("X_test shape", X_test.shape)
print("X_poly_train shape", X_poly_train.shape)
print("X_poly_test shape", X_poly_test.shape)

X_train shape (4432, 76)
X_test shape (1107, 76)
X_poly_train shape (4432, 2853)
X_poly_test shape (1107, 2853)

# First, let's get a baseline view of how lasso performs before we feature engineer

First, grid search for ideal alpha value

In [8]:
import numpy as np
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.linear_model import LogisticRegression

grid = {"C": np.logspace(-5, 5, num=11)}
#Asked ChatGPT why I was getting a solver error
# liblinear or saga support l1; use liblinear for binary problems
lr_est = LogisticRegression(l1_ratio=1, solver="liblinear", max_iter=200, verbose=2)
cv = GridSearchCV(lr_est, param_grid=grid, n_jobs=-1, cv=TimeSeriesSplit(), verbose=2)
cv.fit(X_train, y_train)

Fitting 5 folds for each of 11 candidates, totalling 55 fits
[LibLinear][LibLinear][LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.102586
#nonzeros/#features = 0/77
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.015374
#nonzeros/#features = 0/77
[CV] END ...........................................C=0.0001; total time=   0.0s
=========================
optimization finished, #iter = 0
Objective value = 0.204894
#nonzeros/#features = 0/77
[CV] END ............................................C=1e-05; total time=   0.0s
=========================
optimization finished, #iter = 0
Objective value = 2.560486
#nonzeros/#features = 0/77
[CV] END ...........................................C=0.0001; total time=   0.0s
[CV] END ............................................C=0.001; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.051432
#nonzeros/#features = 0/77
[CV] END ...........................................C=0.0001; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.010259
#nonzeros/#features = 0/77
[CV] END ............................................C=1e-05; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.020489
#nonzeros/#features = 0/77
[CV] END ............................................C=1e-05; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 10.258578
#nonzeros/#features = 0/77
[CV] END .............................................C=0.01; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.025605
#nonzeros/#features = 0/77
[CV] END ............................................C=1e-05; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.256049
#nonzeros/#features = 0/77
[CV] END ...........................................C=0.0001; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.005143
#nonzeros/#features = 0/77
[CV] END ............................................C=1e-05; total time=   0.0s
[LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   4  #CD cycles 5
iter   5  #CD cycles 1
iter   6  #CD cycles 8
iter   7  #CD cycles 1
iter   8  #CD cycles 5
iter   9  #CD cycles 1
iter  10  #CD cycles 2
iter  11  #CD cycles 1
iter  12  #CD cycles 6
=========================
optimization finished, #iter = 12
Objective value = 15.364404
#nonzeros/#features = 2/77
[CV] END .............................................C=0.01; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 5.143152
#nonzeros/#features = 0/77
[CV] END .............................................C=0.01; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.153740
#nonzeros/#features = 0/77
[CV] END ...........................................C=0.0001; total time=   0.0s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.514315
#nonzeros/#features = 0/77
[CV] END ............................................C=0.001; total time=   0.0s
[LibLinear][LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 5
iter   4  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   5  #CD cycles 18
iter   6  #CD cycles 3
iter   4  #CD cycles 1
iter   7  #CD cycles 1
iter   5  #CD cycles 8
iter   6  #CD cycles 1
iter   7  #CD cycles 9
iter   8  #CD cycles 1
iter   9  #CD cycles 9
iter  10  #CD cycles 5
iter  11  #CD cycles 1
iter   8  #CD cycles 61
[LibLinear]iter   9  #CD cycles 8
iter  10  #CD cycles 1
iter  12  #CD cycles 11
iter  13  #CD cycles 7
[LibLinear]iter  14  #CD cycles 4
=========================
optimization finished, #iter = 14
Objective value = 25.462659
#nonzeros/#features = 8/77
=========================
optimization finished, #iter = 0
Objective value = 1.025858
#nonzeros/#features = 0/77
[LibLinear][CV] END ............................................C=0.001; total time=   0.0s
[CV] END .............................................C=0.01; total time=   0.0s
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 3
iter   4  #CD cycles 1
iter   5  #CD cycles 2
iter   6  #CD cycles 1
iter   1  #CD cycles 1
iter   7  #CD cycles 3
iter   8  #CD cycles 1
iter   2  #CD cycles 1
iter   9  #CD cycles 2
iter   3  #CD cycles 1
iter  10  #CD cycles 1
iter  11  #CD cycles 5
iter  12  #CD cycles 1
iter  11  #CD cycles 149
iter  13  #CD cycles 6
iter  12  #CD cycles 5
=========================
optimization finished, #iter = 13
iter  13  #CD cycles 2
Objective value = 20.434440
#nonzeros/#features = 5/77
iter  14  #CD cycles 2
iter   4  #CD cycles 7
iter  15  #CD cycles 6
iter   5  #CD cycles 1
iter  16  #CD cycles 7
iter  17  #CD cycles 1
iter   6  #CD cycles 7
iter   7  #CD cycles 1
iter   8  #CD cycles 1
[CV] END .............................................C=0.01; total time=   0.0s
iter   9  #CD cycles 7
iter  10  #CD cycles 1
iter  11  #CD cycles 10
=========================
optimization finished, #iter = 11
Objective value = 199.564792
#nonzeros/#features = 24/77
[CV] END ..............................................C=0.1; total time=   0.0s
[LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter  18  #CD cycles 227
iter  19  #CD cycles 1
iter   3  #CD cycles 1
[LibLinear]iter   4  #CD cycles 7
iter   5  #CD cycles 1
iter   6  #CD cycles 14
iter   7  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   8  #CD cycles 13
iter   9  #CD cycles 3
iter  10  #CD cycles 1
iter   3  #CD cycles 4
iter   4  #CD cycles 1
iter  11  #CD cycles 14
iter  12  #CD cycles 1
iter  13  #CD cycles 1
=========================
optimization finished, #iter = 13
Objective value = 150.465698
#nonzeros/#features = 24/77
[CV] END ..............................................C=0.1; total time=   0.0s
iter   5  #CD cycles 21
iter   6  #CD cycles 1
iter  20  #CD cycles 362
iter  21  #CD cycles 2
iter  22  #CD cycles 5
iter  23  #CD cycles 1
iter   7  #CD cycles 90
[LibLinear]iter   8  #CD cycles 2
iter   9  #CD cycles 1
[LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 4
iter   4  #CD cycles 1
[LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear]iter   3  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 2
iter   4  #CD cycles 1
iter  24  #CD cycles 412
=========================
optimization finished, #iter = 24
Objective value = 481.747890
#nonzeros/#features = 47/77
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 47
iter   6  #CD cycles 1
[CV] END ..............................................C=1.0; total time=   0.1s
iter   3  #CD cycles 3
iter   4  #CD cycles 20
[LibLinear]iter   4  #CD cycles 1
[LibLinear]iter   5  #CD cycles 3
iter   6  #CD cycles 1
[LibLinear][LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
=========================
optimization finished, #iter = 0
Objective value = 1.537400
#nonzeros/#features = 0/77
iter   1  #CD cycles 1
[LibLinear]iter   5  #CD cycles 31
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   4  #CD cycles 3
iter   3  #CD cycles 3
iter   5  #CD cycles 1
iter   1  #CD cycles 1
iter   6  #CD cycles 3
iter   4  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear]iter   7  #CD cycles 1
iter   8  #CD cycles 5
iter   9  #CD cycles 1
iter   3  #CD cycles 5
iter  10  #CD cycles 14
iter   4  #CD cycles 1
iter   6  #CD cycles 5
iter  11  #CD cycles 5
iter  12  #CD cycles 2
[LibLinear]iter  13  #CD cycles 3
iter  14  #CD cycles 1
iter   7  #CD cycles 1
[LibLinear][LibLinear][CV] END ............................................C=0.001; total time=   0.0s
iter  15  #CD cycles 32
iter  16  #CD cycles 3
iter  17  #CD cycles 6
iter  18  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 17
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   3  #CD cycles 4
iter  19  #CD cycles 46
=========================
optimization finished, #iter = 19
Objective value = 50.114118
#nonzeros/#features = 19/77
iter   4  #CD cycles 1
iter   1  #CD cycles 1
[LibLinear]iter   1  #CD cycles 1
iter   4  #CD cycles 7
iter   5  #CD cycles 1
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   6  #CD cycles 3
iter   6  #CD cycles 3
iter   7  #CD cycles 1
[LibLinear][LibLinear]iter   7  #CD cycles 1
iter   8  #CD cycles 4
iter   3  #CD cycles 4
iter   1  #CD cycles 1
iter   9  #CD cycles 1
iter   4  #CD cycles 1
iter  10  #CD cycles 127
iter   3  #CD cycles 3
iter   5  #CD cycles 62
iter   2  #CD cycles 1
iter  10  #CD cycles 11
iter   4  #CD cycles 1
iter  11  #CD cycles 3
iter  11  #CD cycles 1
iter   6  #CD cycles 5
[LibLinear][CV] END ..............................................C=0.1; total time=   0.0s
[LibLinear][LibLinear]iter   7  #CD cycles 4
iter   3  #CD cycles 1
iter  12  #CD cycles 2
iter   8  #CD cycles 1
[LibLinear]iter  12  #CD cycles 8
iter  13  #CD cycles 3
=========================
optimization finished, #iter = 13
Objective value = 99.941352
#nonzeros/#features = 21/77
[LibLinear][LibLinear]iter  13  #CD cycles 4
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter  14  #CD cycles 1
[LibLinear]iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 51
[LibLinear][LibLinear]iter   5  #CD cycles 19
[LibLinear]iter   3  #CD cycles 6
iter   6  #CD cycles 1
iter   3  #CD cycles 4
iter   4  #CD cycles 1
iter   5  #CD cycles 64
iter   1  #CD cycles 1
iter   4  #CD cycles 1
iter   6  #CD cycles 5
iter   6  #CD cycles 3
iter   1  #CD cycles 1
iter   7  #CD cycles 1
iter   7  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear]iter   2  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear]iter   1  #CD cycles 1
iter   3  #CD cycles 6
[CV] END ..............................................C=0.1; total time=   0.0s
iter   4  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 3
iter   2  #CD cycles 1
iter   1  #CD cycles 1
iter   4  #CD cycles 1
iter   3  #CD cycles 2
iter   3  #CD cycles 2
iter   3  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
[LibLinear]iter   4  #CD cycles 1
iter   4  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
iter   3  #CD cycles 3
[LibLinear][LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
iter   4  #CD cycles 1
iter   3  #CD cycles 2
iter   4  #CD cycles 1
[LibLinear]iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   7  #CD cycles 63
iter   1  #CD cycles 1
iter   3  #CD cycles 3
iter   1  #CD cycles 1
iter   3  #CD cycles 1
iter   5  #CD cycles 65
iter   1  #CD cycles 1
iter   3  #CD cycles 2
iter   4  #CD cycles 1
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   6  #CD cycles 4
iter   7  #CD cycles 1
iter   4  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 27
iter   3  #CD cycles 1
iter   3  #CD cycles 2
iter   4  #CD cycles 1
=========================
optimization finished, #iter = 0
iter   6  #CD cycles 2
Objective value = 2.048943
#nonzeros/#features = 0/77
iter   3  #CD cycles 2
iter   7  #CD cycles 133
iter   8  #CD cycles 10
iter   4  #CD cycles 1
iter   9  #CD cycles 1
iter   5  #CD cycles 50
iter   7  #CD cycles 4
iter   7  #CD cycles 71
iter   8  #CD cycles 10
iter   8  #CD cycles 1
iter   9  #CD cycles 137
iter   8  #CD cycles 2
iter   6  #CD cycles 6
iter   9  #CD cycles 3
iter   4  #CD cycles 29
[CV] END ............................................C=0.001; total time=   0.0s
iter   1  #CD cycles 1
iter   9  #CD cycles 1
iter   5  #CD cycles 50
iter   1  #CD cycles 1
iter   7  #CD cycles 4
[LibLinear]iter  10  #CD cycles 4
iter   8  #CD cycles 1
iter   5  #CD cycles 1
iter   2  #CD cycles 1
iter  11  #CD cycles 1
iter   6  #CD cycles 3
iter  10  #CD cycles 21
iter  11  #CD cycles 3
iter   3  #CD cycles 1
iter   7  #CD cycles 3
iter  12  #CD cycles 3
iter   5  #CD cycles 64
iter  13  #CD cycles 1
iter   8  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   8  #CD cycles 147
iter   2  #CD cycles 1
iter   9  #CD cycles 7
iter   3  #CD cycles 5
iter   4  #CD cycles 1
iter   6  #CD cycles 5
iter  10  #CD cycles 3
iter   7  #CD cycles 1
iter   5  #CD cycles 41
iter  11  #CD cycles 2
iter   2  #CD cycles 1
iter   6  #CD cycles 1
iter  12  #CD cycles 5
iter  13  #CD cycles 2
iter   4  #CD cycles 9
iter  14  #CD cycles 2
iter   3  #CD cycles 2
iter   4  #CD cycles 28
iter  15  #CD cycles 1
iter   5  #CD cycles 1
iter   5  #CD cycles 42
iter   5  #CD cycles 42
iter   5  #CD cycles 1
iter   3  #CD cycles 2
iter   6  #CD cycles 1
iter   6  #CD cycles 2
iter   4  #CD cycles 1
iter   7  #CD cycles 1
iter   4  #CD cycles 25
iter   6  #CD cycles 6
iter   4  #CD cycles 1
iter   4  #CD cycles 23
iter   5  #CD cycles 30
iter   7  #CD cycles 1
iter   5  #CD cycles 1
iter   5  #CD cycles 2
iter   6  #CD cycles 2
iter   8  #CD cycles 136
iter   8  #CD cycles 60
iter   5  #CD cycles 41
iter   9  #CD cycles 1
iter   5  #CD cycles 31
iter   5  #CD cycles 61
iter   5  #CD cycles 30
iter   6  #CD cycles 2
iter   8  #CD cycles 8
iter   5  #CD cycles 56
iter   6  #CD cycles 1
iter   9  #CD cycles 1
iter   7  #CD cycles 4
iter   6  #CD cycles 4
iter   6  #CD cycles 7
iter   7  #CD cycles 1
iter   7  #CD cycles 1
iter   9  #CD cycles 22
iter   7  #CD cycles 1
iter   8  #CD cycles 1
iter   6  #CD cycles 3
iter   6  #CD cycles 4
iter  10  #CD cycles 5
iter  11  #CD cycles 2
iter  12  #CD cycles 3
iter   7  #CD cycles 1
iter   7  #CD cycles 2
iter  13  #CD cycles 2
iter  15  #CD cycles 126
iter  14  #CD cycles 1
iter   8  #CD cycles 1
iter   8  #CD cycles 120
iter  10  #CD cycles 21
iter   8  #CD cycles 134
iter  11  #CD cycles 1
iter   9  #CD cycles 3
iter   9  #CD cycles 7
iter  10  #CD cycles 1
iter  10  #CD cycles 5
iter  16  #CD cycles 25
iter  11  #CD cycles 5
iter  12  #CD cycles 1
iter  17  #CD cycles 2
iter  18  #CD cycles 1
iter  12  #CD cycles 18
iter   8  #CD cycles 143
=========================
optimization finished, #iter = 12
Objective value = 248.566946
#nonzeros/#features = 27/77
iter  14  #CD cycles 179
iter   9  #CD cycles 17
iter  10  #CD cycles 2
iter  11  #CD cycles 1
iter   9  #CD cycles 150
iter  15  #CD cycles 15
iter   5  #CD cycles 25
iter  10  #CD cycles 1
iter  16  #CD cycles 2
iter   6  #CD cycles 1
iter  17  #CD cycles 10
[CV] END ..............................................C=0.1; total time=   0.0s
iter  18  #CD cycles 1
iter   5  #CD cycles 30
iter   8  #CD cycles 150
iter   6  #CD cycles 2
iter   9  #CD cycles 7
iter   9  #CD cycles 131
iter  10  #CD cycles 1
iter   7  #CD cycles 2
iter   8  #CD cycles 1
iter  10  #CD cycles 10
iter   9  #CD cycles 134
iter  11  #CD cycles 2
iter  16  #CD cycles 258
iter  12  #CD cycles 1
iter  17  #CD cycles 5
iter  18  #CD cycles 8
iter  19  #CD cycles 2
iter  20  #CD cycles 2
iter  21  #CD cycles 2
iter  22  #CD cycles 2
iter  10  #CD cycles 14
iter  23  #CD cycles 2
iter  24  #CD cycles 1
iter  11  #CD cycles 2
iter  15  #CD cycles 201
iter  12  #CD cycles 1
iter  16  #CD cycles 7
iter  17  #CD cycles 1
iter  12  #CD cycles 169
iter  13  #CD cycles 8
iter  14  #CD cycles 1
iter   7  #CD cycles 136
iter  10  #CD cycles 99
iter   8  #CD cycles 4
iter   9  #CD cycles 2
iter  11  #CD cycles 2
iter  10  #CD cycles 2
iter  11  #CD cycles 1
iter  12  #CD cycles 1
iter   7  #CD cycles 122
iter   7  #CD cycles 121
iter   8  #CD cycles 3
iter  12  #CD cycles 216
iter  13  #CD cycles 3
iter   8  #CD cycles 8
iter  14  #CD cycles 3
iter  15  #CD cycles 6
iter   9  #CD cycles 4
iter  16  #CD cycles 4
iter  17  #CD cycles 1
iter   9  #CD cycles 7
iter  10  #CD cycles 1
iter  10  #CD cycles 3
iter   8  #CD cycles 116
iter  11  #CD cycles 205
iter  11  #CD cycles 3
iter   8  #CD cycles 132
iter   6  #CD cycles 93
iter  12  #CD cycles 2
iter   9  #CD cycles 2
iter  13  #CD cycles 1
iter  11  #CD cycles 179
iter  10  #CD cycles 1
iter  12  #CD cycles 15
iter  19  #CD cycles 256
iter  20  #CD cycles 2
iter  13  #CD cycles 4
iter   7  #CD cycles 3
iter  14  #CD cycles 1
iter  21  #CD cycles 3
iter   9  #CD cycles 96
iter   9  #CD cycles 10
iter  22  #CD cycles 3
iter  23  #CD cycles 4
iter  13  #CD cycles 163
iter  24  #CD cycles 3
iter   8  #CD cycles 2
iter  25  #CD cycles 2
iter  10  #CD cycles 4
iter  26  #CD cycles 3
iter  27  #CD cycles 1
iter  12  #CD cycles 19
iter  11  #CD cycles 1
iter   9  #CD cycles 2
iter   6  #CD cycles 93
iter  14  #CD cycles 9
iter   8  #CD cycles 102
iter   6  #CD cycles 91
iter  13  #CD cycles 7
iter  15  #CD cycles 2
iter  10  #CD cycles 1
iter  14  #CD cycles 1
iter  16  #CD cycles 1
iter  10  #CD cycles 8
iter   7  #CD cycles 2
iter   9  #CD cycles 3
iter  10  #CD cycles 3
iter   7  #CD cycles 5
iter   9  #CD cycles 106
iter  11  #CD cycles 1
iter  11  #CD cycles 7
iter  10  #CD cycles 2
iter   8  #CD cycles 2
iter  12  #CD cycles 1
iter  11  #CD cycles 2
iter   8  #CD cycles 94
iter   9  #CD cycles 2
iter   8  #CD cycles 9
iter  10  #CD cycles 204
iter   9  #CD cycles 1
iter  10  #CD cycles 1
iter  19  #CD cycles 195
iter   9  #CD cycles 1
iter  12  #CD cycles 3
iter  18  #CD cycles 257
iter  19  #CD cycles 1
iter  20  #CD cycles 3
iter  11  #CD cycles 4
iter  13  #CD cycles 155
iter  21  #CD cycles 1
=========================
optimization finished, #iter = 21
Objective value = 1484.822269
#nonzeros/#features = 53/77
iter  12  #CD cycles 1
iter  10  #CD cycles 134
iter  13  #CD cycles 3
iter  14  #CD cycles 4
iter  14  #CD cycles 1
iter  15  #CD cycles 4
iter  16  #CD cycles 7
[CV] END ..............................................C=1.0; total time=   0.1s
iter  17  #CD cycles 2
iter  18  #CD cycles 1
iter  11  #CD cycles 166
iter  13  #CD cycles 167
iter  14  #CD cycles 1
iter  11  #CD cycles 16
iter  12  #CD cycles 5
iter  12  #CD cycles 1
iter  18  #CD cycles 221
iter  13  #CD cycles 3
iter  14  #CD cycles 1
iter   7  #CD cycles 92
iter   9  #CD cycles 104
iter   8  #CD cycles 2
iter  19  #CD cycles 34
iter   9  #CD cycles 1
iter  10  #CD cycles 4
iter  12  #CD cycles 158
iter  11  #CD cycles 1
iter  20  #CD cycles 9
iter  21  #CD cycles 4
iter  22  #CD cycles 2
iter  13  #CD cycles 5
iter  23  #CD cycles 2
iter  24  #CD cycles 2
iter  14  #CD cycles 1
iter  25  #CD cycles 1
iter  15  #CD cycles 258
iter  28  #CD cycles 256
iter  16  #CD cycles 20
iter  17  #CD cycles 9
iter  18  #CD cycles 1
iter  15  #CD cycles 185
iter  29  #CD cycles 33
iter  16  #CD cycles 3
iter  30  #CD cycles 9
iter  31  #CD cycles 4
iter  17  #CD cycles 10
iter  32  #CD cycles 4
iter  18  #CD cycles 1
iter  33  #CD cycles 1
iter  17  #CD cycles 163
iter  18  #CD cycles 5
iter  19  #CD cycles 4
iter  14  #CD cycles 128
iter  20  #CD cycles 1
iter  11  #CD cycles 146
iter  15  #CD cycles 8
iter  12  #CD cycles 4
iter  20  #CD cycles 315
iter  13  #CD cycles 1
iter  21  #CD cycles 1
iter  16  #CD cycles 5
iter  17  #CD cycles 1
iter  11  #CD cycles 151
iter  12  #CD cycles 1
iter  12  #CD cycles 144
iter  13  #CD cycles 4
iter  19  #CD cycles 169
iter  20  #CD cycles 1
iter  13  #CD cycles 133
iter  13  #CD cycles 152
iter  14  #CD cycles 4
iter  14  #CD cycles 1
iter  14  #CD cycles 1
iter  15  #CD cycles 1
iter  15  #CD cycles 172
iter  16  #CD cycles 3
iter  26  #CD cycles 279
iter  17  #CD cycles 6
iter  18  #CD cycles 2
iter  19  #CD cycles 1
iter  27  #CD cycles 23
iter  28  #CD cycles 2
iter  29  #CD cycles 7
iter  30  #CD cycles 7
iter  31  #CD cycles 2
iter  32  #CD cycles 1
iter  12  #CD cycles 130
iter  13  #CD cycles 7
iter  15  #CD cycles 181
iter  16  #CD cycles 4
iter  17  #CD cycles 2
iter  19  #CD cycles 199
=========================
optimization finished, #iter = 19
Objective value = 978.062177
#nonzeros/#features = 52/77

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=LogisticRegression(l1_ratio=1, max_iter=200,
                                          solver='liblinear', verbose=2),
             n_jobs=-1,
             param_grid={'C': array([1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02,
       1.e+03, 1.e+04, 1.e+05])},
             verbose=2)

The model chose 26 nonzero features.

Let's see which C was best (inverse of alpha)

In [9]:
cv.best_params_

{'C': np.float64(0.1)}

So C of 0.1 or alpha of 10 is best.

In [10]:
best_estimator = cv.best_estimator_
best_estimator.score(X_train, y_train)

0.5943140794223827

In [11]:
best_estimator.score(X_test, y_test)

0.5709123757904245

It is able to score ~2% better than baseline on the test set.

How did lasso distribute weights?

In [12]:
weights = pd.DataFrame()
weights["Feature"] = X_train.columns
weights["Weight"] = best_estimator.coef_[0]
weights = weights.sort_values(by="Weight", ascending = False)
display(weights.head(10))
display(weights.tail(10))

                                   Feature    Weight
5        previous_10_games_team1_max_kills  0.123737
31     previous_10_games_team1_median_kast  0.085156
30        previous_10_games_team1_min_kast  0.074166
55  previous_10_games_team2_median_assists  0.070546
0      team1_previous_10_average_map_score  0.052362
24         previous_10_games_team1_min_adr  0.037635
63        previous_10_games_team2_std_kast  0.037346
15     previous_10_games_team1_std_assists  0.026023
46    previous_10_games_team2_range_deaths  0.023498
33      previous_10_games_team1_std_kddiff  0.015203

                                  Feature    Weight
7    previous_10_games_team1_median_kills -0.015606
62   previous_10_games_team2_average_kast -0.019173
69     previous_10_games_team2_std_kddiff -0.021030
18    previous_10_games_team1_min_assists -0.027297
11     previous_10_games_team1_max_deaths -0.062317
9      previous_10_games_team1_std_deaths -0.077430
60        previous_10_games_team2_min_adr -0.078224
41      previous_10_games_team2_max_kills -0.089118
1     team2_previous_10_average_map_score -0.110423
73  previous_10_games_team2_median_kddiff -0.110749

The model seems to find team2 previous median kddiff, team2 previous average map score, and team 1 previous max kills the most important, which is different from what the collinear feature-pruned model valued. The collinear feature-pruned logistic regressor performed slightly better by ~0.3%.

# Now, let's try doing the feature engineered set.

In [13]:
cv = GridSearchCV(lr_est, param_grid=grid, n_jobs=-1, cv=TimeSeriesSplit(), verbose=2)
cv.fit(X_poly_train, y_train)

Fitting 5 folds for each of 11 candidates, totalling 55 fits
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.005143
#nonzeros/#features = 0/2854
[LibLinear][CV] END ............................................C=1e-05; total time=   0.1s
[LibLinear][LibLinear][LibLinear][LibLinear][LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.051432
#nonzeros/#features = 0/2854
[LibLinear][CV] END ...........................................C=0.0001; total time=   0.1s
[LibLinear][LibLinear][LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.010259
#nonzeros/#features = 0/2854
[CV] END ............................................C=1e-05; total time=   0.2s
=========================
optimization finished, #iter = 0
Objective value = 0.025605
#nonzeros/#features = 0/2854
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.020489
#nonzeros/#features = 0/2854
[LibLinear][LibLinear][CV] END ............................................C=1e-05; total time=   0.3s
[CV] END ............................................C=1e-05; total time=   0.3s
=========================
optimization finished, #iter = 0
Objective value = 0.153740
#nonzeros/#features = 0/2854
=========================
optimization finished, #iter = 0
Objective value = 0.102586
#nonzeros/#features = 0/2854
=========================
optimization finished, #iter = 0
Objective value = 0.015374
#nonzeros/#features = 0/2854
[CV] END ...........................................C=0.0001; total time=   0.3s
[CV] END ...........................................C=0.0001; total time=   0.2s
[LibLinear][CV] END ............................................C=1e-05; total time=   0.3s
[LibLinear][LibLinear]iter   1  #CD cycles 1
[LibLinear][LibLinear]=========================
optimization finished, #iter = 0
Objective value = 0.256049
#nonzeros/#features = 0/2854
iter   2  #CD cycles 1
=========================
optimization finished, #iter = 0
Objective value = 0.204894
#nonzeros/#features = 0/2854
[CV] END ...........................................C=0.0001; total time=   0.4s
iter   3  #CD cycles 1
[CV] END ...........................................C=0.0001; total time=   0.3s
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 2.560486
#nonzeros/#features = 0/2854
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
[CV] END ............................................C=0.001; total time=   0.4s
iter   3  #CD cycles 1
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   4  #CD cycles 1
iter   3  #CD cycles 1
iter   5  #CD cycles 1
iter   1  #CD cycles 1
iter   6  #CD cycles 3
iter   3  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
=========================
optimization finished, #iter = 0
Objective value = 2.048943
#nonzeros/#features = 0/2854
iter   7  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   3  #CD cycles 1
iter   8  #CD cycles 10
[CV] END ............................................C=0.001; total time=   0.3s
iter   4  #CD cycles 1
iter   4  #CD cycles 1
[LibLinear]iter   5  #CD cycles 1
iter   9  #CD cycles 1
iter   5  #CD cycles 1
iter   2  #CD cycles 1
iter   6  #CD cycles 10
iter  10  #CD cycles 53
iter   7  #CD cycles 1
iter   6  #CD cycles 9
iter   8  #CD cycles 14
=========================
optimization finished, #iter = 10
Objective value = 20.413081
#nonzeros/#features = 9/2854
iter   7  #CD cycles 1
iter   9  #CD cycles 1
[LibLinear]iter   4  #CD cycles 7
iter   3  #CD cycles 1
iter  10  #CD cycles 30
iter   8  #CD cycles 16
[CV] END .............................................C=0.01; total time=   0.5s
iter   1  #CD cycles 1
=========================
optimization finished, #iter = 10
Objective value = 98.914495
#nonzeros/#features = 59/2854
iter   5  #CD cycles 1
iter   9  #CD cycles 1
[LibLinear][CV] END ..............................................C=0.1; total time=   0.3s
iter  10  #CD cycles 29
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter  11  #CD cycles 1
iter   3  #CD cycles 1
iter   2  #CD cycles 1
=========================
optimization finished, #iter = 11
Objective value = 149.104792
#nonzeros/#features = 73/2854
iter   1  #CD cycles 1
[LibLinear]iter   4  #CD cycles 5
=========================
optimization finished, #iter = 0
Objective value = 0.514315
#nonzeros/#features = 0/2854
iter   2  #CD cycles 1
[CV] END ..............................................C=0.1; total time=   0.4s
iter   5  #CD cycles 1
iter   4  #CD cycles 25
iter   3  #CD cycles 1
[CV] END ............................................C=0.001; total time=   0.1s
iter   3  #CD cycles 1
[LibLinear]iter   6  #CD cycles 23
iter   7  #CD cycles 4
[LibLinear]iter   8  #CD cycles 1
[LibLinear][LibLinear][LibLinear][LibLinear][LibLinear][LibLinear]iter   9  #CD cycles 78
iter   5  #CD cycles 6
[LibLinear]iter  10  #CD cycles 9
iter  11  #CD cycles 1
[LibLinear][LibLinear]iter   6  #CD cycles 1
[LibLinear][LibLinear][LibLinear][LibLinear][LibLinear][LibLinear][LibLinear]iter   1  #CD cycles 1
iter   1  #CD cycles 1
[LibLinear]iter   4  #CD cycles 13
[LibLinear][LibLinear]iter   1  #CD cycles 1
[LibLinear]iter   2  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear][LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
[LibLinear]iter  12  #CD cycles 266
[LibLinear]=========================
optimization finished, #iter = 0
Objective value = 5.143152
#nonzeros/#features = 0/2854
iter   3  #CD cycles 1
iter  13  #CD cycles 10
iter   3  #CD cycles 1
iter   3  #CD cycles 1
[LibLinear]iter   1  #CD cycles 1
iter  14  #CD cycles 13
iter   4  #CD cycles 1
iter  15  #CD cycles 3
iter   2  #CD cycles 1
[LibLinear]iter  16  #CD cycles 3
iter  17  #CD cycles 1
iter   1  #CD cycles 1
iter   5  #CD cycles 1
[CV] END .............................................C=0.01; total time=   0.3s
iter   6  #CD cycles 7
iter   3  #CD cycles 1
iter   2  #CD cycles 1
iter   7  #CD cycles 1
iter   2  #CD cycles 1
iter   1  #CD cycles 1
=========================
optimization finished, #iter = 0
Objective value = 1.025858
#nonzeros/#features = 0/2854
iter   8  #CD cycles 13
iter   5  #CD cycles 2
iter   9  #CD cycles 1
iter   3  #CD cycles 1
iter  10  #CD cycles 36
[LibLinear]iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter  11  #CD cycles 3
[CV] END ............................................C=0.001; total time=   0.4s
iter   4  #CD cycles 13
[LibLinear]=========================
optimization finished, #iter = 11
Objective value = 49.292691
#nonzeros/#features = 42/2854
iter   1  #CD cycles 1
[LibLinear]iter   3  #CD cycles 1
iter   6  #CD cycles 32
[CV] END ..............................................C=0.1; total time=   0.4s
iter   1  #CD cycles 1
iter   6  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   4  #CD cycles 6
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 3
iter   5  #CD cycles 1
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   3  #CD cycles 1
iter   5  #CD cycles 3
iter   3  #CD cycles 1
iter  18  #CD cycles 582
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter  19  #CD cycles 32
iter   4  #CD cycles 1
iter  20  #CD cycles 1
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   7  #CD cycles 5
iter   3  #CD cycles 1
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 1
=========================
optimization finished, #iter = 0
Objective value = 1.537400
#nonzeros/#features = 0/2854
iter   6  #CD cycles 1
iter   6  #CD cycles 1
iter   3  #CD cycles 1
iter   4  #CD cycles 1
iter   8  #CD cycles 1
iter   7  #CD cycles 1
iter   2  #CD cycles 1
[CV] END ............................................C=0.001; total time=   0.5s
iter   4  #CD cycles 27
iter   3  #CD cycles 1
iter   8  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   5  #CD cycles 1
iter   9  #CD cycles 104
iter   1  #CD cycles 1
iter   3  #CD cycles 1
iter  10  #CD cycles 2
iter   6  #CD cycles 5
iter   4  #CD cycles 28
iter   4  #CD cycles 1
iter  11  #CD cycles 12
iter   4  #CD cycles 25
iter   4  #CD cycles 22
iter   3  #CD cycles 1
iter  12  #CD cycles 3
iter   7  #CD cycles 1
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter  13  #CD cycles 3
iter   8  #CD cycles 5
iter  14  #CD cycles 4
iter   5  #CD cycles 3
iter   1  #CD cycles 1
iter  15  #CD cycles 1
iter   5  #CD cycles 10
iter   1  #CD cycles 1
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter  16  #CD cycles 226
iter   9  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   1  #CD cycles 1
=========================
optimization finished, #iter = 16
Objective value = 10.257199
#nonzeros/#features = 3/2854
iter   6  #CD cycles 2
iter   6  #CD cycles 1
iter   5  #CD cycles 6
iter   6  #CD cycles 33
iter   3  #CD cycles 1
iter   5  #CD cycles 10
iter  10  #CD cycles 3
iter   7  #CD cycles 1
[CV] END .............................................C=0.01; total time=   0.7s
iter   1  #CD cycles 1
iter   4  #CD cycles 10
iter   4  #CD cycles 29
iter   6  #CD cycles 1
iter   2  #CD cycles 1
iter   4  #CD cycles 29
iter   3  #CD cycles 1
iter  21  #CD cycles 759
iter   2  #CD cycles 1
=========================
optimization finished, #iter = 21
Objective value = 403.575914
#nonzeros/#features = 218/2854
iter   7  #CD cycles 3
iter   2  #CD cycles 1
iter   4  #CD cycles 1
=========================
optimization finished, #iter = 10
Objective value = 15.357826
#nonzeros/#features = 6/2854
iter   2  #CD cycles 1
iter   6  #CD cycles 3
iter   8  #CD cycles 1
iter   5  #CD cycles 7
[CV] END ..............................................C=1.0; total time=   0.9s
iter   7  #CD cycles 9
iter   7  #CD cycles 1
iter   1  #CD cycles 1
iter   5  #CD cycles 3
[CV] END .............................................C=0.01; total time=   0.8s
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   6  #CD cycles 1
iter   1  #CD cycles 1
iter   8  #CD cycles 1
iter   3  #CD cycles 1
iter   3  #CD cycles 1
iter   3  #CD cycles 1
iter   6  #CD cycles 1
iter   5  #CD cycles 1
iter   4  #CD cycles 20
iter   1  #CD cycles 1
iter   5  #CD cycles 9
iter   2  #CD cycles 1
iter   2  #CD cycles 1
iter   5  #CD cycles 9
iter   3  #CD cycles 1
iter   9  #CD cycles 18
iter   7  #CD cycles 6
iter   6  #CD cycles 1
iter   6  #CD cycles 1
iter   8  #CD cycles 1
iter   3  #CD cycles 1
iter  10  #CD cycles 3
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   1  #CD cycles 1
iter  11  #CD cycles 1
iter   1  #CD cycles 1
iter   4  #CD cycles 1
iter   9  #CD cycles 27
iter  10  #CD cycles 1
iter   5  #CD cycles 6
iter   5  #CD cycles 1
iter   3  #CD cycles 1
iter  12  #CD cycles 43
iter   6  #CD cycles 1
iter   4  #CD cycles 24
iter   2  #CD cycles 1
iter  11  #CD cycles 47
iter   4  #CD cycles 5
iter   6  #CD cycles 6
iter   2  #CD cycles 1
iter  13  #CD cycles 1
iter  12  #CD cycles 1
iter   4  #CD cycles 17
iter   7  #CD cycles 1
=========================
optimization finished, #iter = 13
Objective value = 246.335850
#nonzeros/#features = 97/2854
iter   4  #CD cycles 19
iter   3  #CD cycles 1
iter   5  #CD cycles 1
iter   4  #CD cycles 24
iter  13  #CD cycles 62
[CV] END ..............................................C=0.1; total time=   1.2s
iter   8  #CD cycles 5
iter   4  #CD cycles 6
=========================
optimization finished, #iter = 13
Objective value = 197.500493
#nonzeros/#features = 70/2854
iter   3  #CD cycles 1
iter   4  #CD cycles 18
[CV] END ..............................................C=0.1; total time=   1.1s
iter   5  #CD cycles 7
iter   9  #CD cycles 1
iter   5  #CD cycles 1
iter   4  #CD cycles 16
iter   6  #CD cycles 1
iter   5  #CD cycles 5
iter   5  #CD cycles 4
iter  10  #CD cycles 7
iter   5  #CD cycles 6
iter   4  #CD cycles 12
iter   6  #CD cycles 1
iter   4  #CD cycles 10
=========================
optimization finished, #iter = 10
Objective value = 25.430206
#nonzeros/#features = 14/2854
iter   6  #CD cycles 1
iter   4  #CD cycles 13
iter   4  #CD cycles 18
iter   5  #CD cycles 4
[CV] END .............................................C=0.01; total time=   1.2s
iter   6  #CD cycles 3
iter   5  #CD cycles 1
iter   5  #CD cycles 4
iter   9  #CD cycles 144
iter   7  #CD cycles 1
iter   6  #CD cycles 1
iter   5  #CD cycles 2
iter   5  #CD cycles 3
iter   4  #CD cycles 9
iter   6  #CD cycles 1
iter  10  #CD cycles 9
iter  11  #CD cycles 1
iter   4  #CD cycles 13
iter   6  #CD cycles 1
iter   5  #CD cycles 4
iter   6  #CD cycles 1
iter   5  #CD cycles 1
iter   6  #CD cycles 1
iter   4  #CD cycles 9
iter   5  #CD cycles 3
iter   5  #CD cycles 1
iter   4  #CD cycles 9
iter   6  #CD cycles 1
iter   5  #CD cycles 1
iter   9  #CD cycles 152
iter  10  #CD cycles 8
iter   6  #CD cycles 32
iter  11  #CD cycles 1
iter   7  #CD cycles 5
iter   6  #CD cycles 32
iter   8  #CD cycles 1
iter   7  #CD cycles 158
iter   7  #CD cycles 3
iter   8  #CD cycles 1
iter  12  #CD cycles 393
iter  13  #CD cycles 19
iter  14  #CD cycles 1
iter   8  #CD cycles 52
iter   9  #CD cycles 12
iter  10  #CD cycles 5
iter  11  #CD cycles 1
iter  15  #CD cycles 834
iter  16  #CD cycles 49
iter  17  #CD cycles 2
iter  18  #CD cycles 1
iter   7  #CD cycles 309
iter   8  #CD cycles 283
iter  12  #CD cycles 455
iter   9  #CD cycles 168
iter   8  #CD cycles 306
iter  13  #CD cycles 17
iter  14  #CD cycles 7
iter  15  #CD cycles 1
iter  10  #CD cycles 17
iter   7  #CD cycles 314
iter  11  #CD cycles 5
iter  12  #CD cycles 4
iter  13  #CD cycles 1
iter   9  #CD cycles 159
iter  10  #CD cycles 12
WARNING: reaching max number of inner iterations
iter  19  #CD cycles 1000
=========================
optimization finished, #iter = 19
Objective value = 860.807121
#nonzeros/#features = 304/2854
iter  11  #CD cycles 8
[CV] END ..............................................C=1.0; total time=   4.1s
iter  12  #CD cycles 1
iter   8  #CD cycles 112
iter   9  #CD cycles 105
iter   7  #CD cycles 273
iter   9  #CD cycles 113
iter   8  #CD cycles 113
iter  10  #CD cycles 36
iter   9  #CD cycles 46
iter  10  #CD cycles 3
iter  11  #CD cycles 5
iter  11  #CD cycles 2
iter  12  #CD cycles 1
iter  12  #CD cycles 1
iter  10  #CD cycles 39
iter  12  #CD cycles 539
iter  11  #CD cycles 11
iter  12  #CD cycles 1
iter   9  #CD cycles 49
iter  10  #CD cycles 2
iter  11  #CD cycles 2
iter  12  #CD cycles 1
iter   8  #CD cycles 69
iter  13  #CD cycles 144
iter  14  #CD cycles 18
iter   9  #CD cycles 21
iter  15  #CD cycles 12
iter  10  #CD cycles 1
iter  16  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  16  #CD cycles 1000
iter  17  #CD cycles 81
iter  18  #CD cycles 14
iter  14  #CD cycles 515
iter  19  #CD cycles 15
iter  20  #CD cycles 4
iter  21  #CD cycles 1
iter  15  #CD cycles 19
iter  16  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  17  #CD cycles 1000
iter   7  #CD cycles 299
iter   7  #CD cycles 466
iter  13  #CD cycles 503
iter  14  #CD cycles 15
iter  15  #CD cycles 8
iter  16  #CD cycles 1
iter   7  #CD cycles 253
iter   7  #CD cycles 484
iter   6  #CD cycles 195
iter  18  #CD cycles 752
iter  19  #CD cycles 26
iter  20  #CD cycles 14
iter  21  #CD cycles 1
iter   8  #CD cycles 478
iter   7  #CD cycles 489
iter   8  #CD cycles 74
iter   8  #CD cycles 44
WARNING: reaching max number of inner iterations
iter  22  #CD cycles 1000
=========================
optimization finished, #iter = 22
Objective value = 1348.152364
#nonzeros/#features = 343/2854
[CV] END ..............................................C=1.0; total time=   9.5s
iter   9  #CD cycles 9
iter   9  #CD cycles 17
iter  10  #CD cycles 3
iter  10  #CD cycles 6
iter  11  #CD cycles 1
iter  11  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  22  #CD cycles 1000
iter   8  #CD cycles 150
iter   7  #CD cycles 380
iter   7  #CD cycles 40
iter   8  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  17  #CD cycles 1000
iter   6  #CD cycles 281
iter   8  #CD cycles 169
iter   9  #CD cycles 45
iter  10  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  23  #CD cycles 1000
iter   9  #CD cycles 154
iter  13  #CD cycles 873
iter   9  #CD cycles 45
iter  10  #CD cycles 7
iter   6  #CD cycles 277
iter  11  #CD cycles 6
iter   6  #CD cycles 268
iter  12  #CD cycles 2
iter  13  #CD cycles 1
iter   7  #CD cycles 366
iter  10  #CD cycles 61
iter   8  #CD cycles 163
iter   6  #CD cycles 279
iter   7  #CD cycles 511
iter  11  #CD cycles 4
iter   7  #CD cycles 513
WARNING: reaching max number of inner iterations
iter  24  #CD cycles 1000
iter  12  #CD cycles 5
iter  13  #CD cycles 2
iter  13  #CD cycles 929
iter  14  #CD cycles 2
iter  15  #CD cycles 1
iter  18  #CD cycles 446
iter  19  #CD cycles 25
iter  20  #CD cycles 1
iter   7  #CD cycles 378
iter   8  #CD cycles 94
iter  13  #CD cycles 924
WARNING: reaching max number of inner iterations
iter  17  #CD cycles 1000
iter   7  #CD cycles 54
iter   9  #CD cycles 48
iter  13  #CD cycles 918
iter   7  #CD cycles 374
iter  10  #CD cycles 4
iter   9  #CD cycles 19
iter  11  #CD cycles 3
iter  12  #CD cycles 2
iter  10  #CD cycles 4
iter  13  #CD cycles 3
WARNING: reaching max number of inner iterations
iter  25  #CD cycles 1000
iter  11  #CD cycles 1
iter  14  #CD cycles 2
iter   8  #CD cycles 9
iter  15  #CD cycles 1
iter   7  #CD cycles 488
iter   9  #CD cycles 5
iter  10  #CD cycles 1
iter   7  #CD cycles 508
iter  26  #CD cycles 477
iter  14  #CD cycles 333
iter  27  #CD cycles 46
iter  28  #CD cycles 15
iter  29  #CD cycles 21
iter  30  #CD cycles 32
iter  31  #CD cycles 19
iter  32  #CD cycles 5
iter  33  #CD cycles 3
iter  34  #CD cycles 1
iter  15  #CD cycles 69
iter   7  #CD cycles 58
iter  16  #CD cycles 17
iter  17  #CD cycles 1
iter   7  #CD cycles 57
iter  18  #CD cycles 378
iter   7  #CD cycles 58
iter  19  #CD cycles 1
iter   8  #CD cycles 7
iter   9  #CD cycles 1
iter   8  #CD cycles 7
iter   8  #CD cycles 10
WARNING: reaching max number of inner iterations
iter  35  #CD cycles 1000
iter   9  #CD cycles 5
iter   9  #CD cycles 4
iter  14  #CD cycles 367
iter  10  #CD cycles 2
iter  10  #CD cycles 2
iter   8  #CD cycles 98
iter  11  #CD cycles 4
iter  11  #CD cycles 5
iter  12  #CD cycles 1
iter  12  #CD cycles 1
iter   9  #CD cycles 8
iter  14  #CD cycles 366
iter   8  #CD cycles 147
iter  10  #CD cycles 4
iter   8  #CD cycles 151
iter  11  #CD cycles 6
iter  15  #CD cycles 108
WARNING: reaching max number of inner iterations
iter  36  #CD cycles 1000
iter  12  #CD cycles 3
=========================
optimization finished, #iter = 36
Objective value = 1847.646262
#nonzeros/#features = 535/2854
WARNING: reaching max number of inner iterations
iter  21  #CD cycles 1000
=========================
optimization finished, #iter = 21
Objective value = 1812.662339
#nonzeros/#features = 384/2854
[CV] END .............................................C=10.0; total time=  13.9s
iter  13  #CD cycles 1
iter   8  #CD cycles 100
iter  16  #CD cycles 12
[CV] END ..............................................C=1.0; total time=  13.9s
iter  17  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  11  #CD cycles 1000
iter  14  #CD cycles 373
iter  15  #CD cycles 118
iter  16  #CD cycles 6
iter  17  #CD cycles 2
iter   8  #CD cycles 104
iter  18  #CD cycles 3
iter  19  #CD cycles 1
iter   9  #CD cycles 40
iter  10  #CD cycles 1
iter   9  #CD cycles 20
iter   9  #CD cycles 40
iter  10  #CD cycles 1
iter  10  #CD cycles 2
iter   9  #CD cycles 12
iter  11  #CD cycles 2
iter  12  #CD cycles 1
iter  10  #CD cycles 3
iter  11  #CD cycles 4
iter  12  #CD cycles 1
iter   8  #CD cycles 154
iter  15  #CD cycles 100
iter  16  #CD cycles 7
iter  17  #CD cycles 8
iter  18  #CD cycles 1
iter   8  #CD cycles 165
iter   9  #CD cycles 30
iter  10  #CD cycles 2
iter  11  #CD cycles 2
iter  12  #CD cycles 1
iter   9  #CD cycles 30
iter  10  #CD cycles 3

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 103  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  81  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  99  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 105  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  93  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  81  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 104  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  92  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  82  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 100  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 106  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  94  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  82  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 105  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  93  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 101  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  83  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 107  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  95  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 106  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  83  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 108  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  94  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 102  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  84  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  96  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 107  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  84  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 109  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  97  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 103  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  95  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  85  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 108  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 110  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  98  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  85  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 104  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  96  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 109  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  86  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 111  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  99  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  86  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 105  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 110  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  97  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  87  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 112  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 100  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 111  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 106  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  87  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  98  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 113  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  88  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 101  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 112  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 107  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  88  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 114  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 102  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  99  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  89  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 113  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 1616723.358486
#nonzeros/#features = 2854/2854
[CV] END ..........................................C=10000.0; total time=29.4min
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 108  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 115  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 103  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  89  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 100  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 114  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  90  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 116  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 109  #CD cycles 1000
iter 115  #CD cycles 586
WARNING: reaching max number of inner iterations
iter 104  #CD cycles 1000
iter 116  #CD cycles 57
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
iter 117  #CD cycles 142
iter 118  #CD cycles 1
WARNING: reaching max number of inner iterations
iter  90  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 101  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  91  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 117  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 105  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 110  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 119  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  91  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 102  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  92  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 118  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 106  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 120  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 111  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  92  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 119  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 107  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 103  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  93  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 121  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 112  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 120  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 108  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  93  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 122  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 104  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  94  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 113  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 121  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 109  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 123  #CD cycles 1000
iter 110  #CD cycles 258
iter 111  #CD cycles 37
WARNING: reaching max number of inner iterations
iter  94  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 105  #CD cycles 1000
iter 122  #CD cycles 632
iter 123  #CD cycles 12
WARNING: reaching max number of inner iterations
iter 114  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  95  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
iter 124  #CD cycles 247
iter 112  #CD cycles 704
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 124  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
iter 125  #CD cycles 511
iter 113  #CD cycles 468
iter 114  #CD cycles 19
iter 115  #CD cycles 43
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
iter 126  #CD cycles 189
WARNING: reaching max number of inner iterations
iter  95  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 115  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 106  #CD cycles 1000
iter 127  #CD cycles 201
iter 128  #CD cycles 8
iter 129  #CD cycles 66
WARNING: reaching max number of inner iterations
iter  96  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
iter 130  #CD cycles 233
iter 116  #CD cycles 567
iter 131  #CD cycles 86
WARNING: reaching max number of inner iterations
iter 125  #CD cycles 1000
iter 117  #CD cycles 133
iter 118  #CD cycles 25
iter 119  #CD cycles 64
iter 120  #CD cycles 10
iter 121  #CD cycles 1
iter 132  #CD cycles 197
iter 133  #CD cycles 54
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
iter 134  #CD cycles 16
iter 135  #CD cycles 98
iter 136  #CD cycles 40
iter 137  #CD cycles 4
iter 138  #CD cycles 66
iter 139  #CD cycles 17
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
iter 140  #CD cycles 45
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  96  #CD cycles 1000
iter 141  #CD cycles 141
iter 142  #CD cycles 11
WARNING: reaching max number of inner iterations
iter 116  #CD cycles 1000
iter 143  #CD cycles 20
iter 144  #CD cycles 34
iter 145  #CD cycles 45
iter 146  #CD cycles 17
WARNING: reaching max number of inner iterations
iter 107  #CD cycles 1000
iter 147  #CD cycles 29
iter 148  #CD cycles 3
iter 149  #CD cycles 17
iter 150  #CD cycles 4
iter 151  #CD cycles 10
iter 152  #CD cycles 18
iter 153  #CD cycles 3
iter 154  #CD cycles 17
WARNING: reaching max number of inner iterations
iter  97  #CD cycles 1000
iter 155  #CD cycles 38
iter 156  #CD cycles 29
iter 157  #CD cycles 11
iter 158  #CD cycles 11
iter 159  #CD cycles 14
iter 160  #CD cycles 3
WARNING: reaching max number of inner iterations
iter 126  #CD cycles 1000
iter 161  #CD cycles 37
iter 162  #CD cycles 7
iter 163  #CD cycles 13
iter 164  #CD cycles 6
iter 165  #CD cycles 21
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
iter 166  #CD cycles 10
iter 167  #CD cycles 6
iter 168  #CD cycles 14
iter 169  #CD cycles 5
iter 170  #CD cycles 12
WARNING: reaching max number of inner iterations
iter 122  #CD cycles 1000
iter 171  #CD cycles 9
iter 172  #CD cycles 2
iter 173  #CD cycles 35
iter 174  #CD cycles 3
iter 175  #CD cycles 40
iter 176  #CD cycles 13
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
iter 177  #CD cycles 35
iter 178  #CD cycles 3
iter 179  #CD cycles 8
iter 180  #CD cycles 4
iter 181  #CD cycles 13
iter 182  #CD cycles 24
iter 183  #CD cycles 30
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
iter 184  #CD cycles 11
iter 185  #CD cycles 2
iter 186  #CD cycles 12
iter 187  #CD cycles 3
iter 188  #CD cycles 91
iter 189  #CD cycles 15
iter 190  #CD cycles 13
iter 191  #CD cycles 23
iter 192  #CD cycles 14
iter 193  #CD cycles 1
WARNING: reaching max number of inner iterations
iter 117  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  97  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 127  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 108  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 123  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  98  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 118  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 128  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  98  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 124  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 109  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  99  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
iter 110  #CD cycles 241
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 129  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 119  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 125  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter  99  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 100  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 111  #CD cycles 1000
iter 112  #CD cycles 35
iter 113  #CD cycles 34
WARNING: reaching max number of inner iterations
iter 130  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 126  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 120  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
iter 114  #CD cycles 357
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
iter 115  #CD cycles 123
iter 116  #CD cycles 39
iter 117  #CD cycles 19
iter 118  #CD cycles 2
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
iter 119  #CD cycles 31
WARNING: reaching max number of inner iterations
iter 100  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 101  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
iter 120  #CD cycles 356
iter 121  #CD cycles 7
iter 122  #CD cycles 2
WARNING: reaching max number of inner iterations
iter 127  #CD cycles 1000
iter 123  #CD cycles 57
iter 124  #CD cycles 5
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 121  #CD cycles 1000
iter 125  #CD cycles 212
iter 126  #CD cycles 1
iter 102  #CD cycles 472
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 101  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 128  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 122  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 103  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 127  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 102  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 129  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
iter 104  #CD cycles 586
WARNING: reaching max number of inner iterations
iter 123  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 76828884.460258
#nonzeros/#features = 2854/2854
[CV] END .........................................C=100000.0; total time=34.9min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 128  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
iter 103  #CD cycles 791
iter 105  #CD cycles 599
iter 106  #CD cycles 24
WARNING: reaching max number of inner iterations
iter 130  #CD cycles 1000
iter 104  #CD cycles 204
iter 105  #CD cycles 38
iter 106  #CD cycles 9
iter 107  #CD cycles 40
iter 107  #CD cycles 356
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 124  #CD cycles 1000
iter 108  #CD cycles 199
iter 108  #CD cycles 94
iter 109  #CD cycles 12
iter 110  #CD cycles 31
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
iter 109  #CD cycles 204
iter 111  #CD cycles 167
iter 112  #CD cycles 29
iter 113  #CD cycles 7
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
iter 114  #CD cycles 42
iter 110  #CD cycles 137
WARNING: reaching max number of inner iterations
iter 129  #CD cycles 1000
iter 111  #CD cycles 26
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
iter 112  #CD cycles 26
iter 115  #CD cycles 170
iter 116  #CD cycles 5
iter 117  #CD cycles 20
iter 118  #CD cycles 4
iter 119  #CD cycles 26
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
iter 120  #CD cycles 58
iter 121  #CD cycles 11
iter 113  #CD cycles 225
iter 122  #CD cycles 30
iter 114  #CD cycles 1
iter 123  #CD cycles 16
iter 124  #CD cycles 30
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
iter 125  #CD cycles 28
iter 126  #CD cycles 7
iter 127  #CD cycles 6
iter 128  #CD cycles 18
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
iter 129  #CD cycles 14
iter 130  #CD cycles 46
iter 131  #CD cycles 5
iter 132  #CD cycles 48
iter 133  #CD cycles 32
iter 134  #CD cycles 15
WARNING: reaching max number of inner iterations
iter 125  #CD cycles 1000
iter 135  #CD cycles 36
iter 136  #CD cycles 10
iter 137  #CD cycles 12
iter 138  #CD cycles 35
iter 139  #CD cycles 3
iter 140  #CD cycles 15
iter 141  #CD cycles 38
iter 142  #CD cycles 15
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
iter 143  #CD cycles 50
iter 144  #CD cycles 6
iter 145  #CD cycles 7
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
iter 146  #CD cycles 4
iter 147  #CD cycles 23
iter 148  #CD cycles 6
iter 149  #CD cycles 1
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 130  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 115  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 126  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 116  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 127  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 117  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 128  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 129  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 118  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 130  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 119  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 120  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 121  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 122  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 123  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 124  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 11004224.980730
#nonzeros/#features = 2854/2854
[CV] END .........................................C=100000.0; total time=39.4min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 125  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 126  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 127  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 147398.985572
#nonzeros/#features = 2804/2854
[CV] END ...........................................C=1000.0; total time=40.9min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 128  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 129  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 130  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 131  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 132  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 133  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 134  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 135  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 136  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 137  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 138  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 91770.541521
#nonzeros/#features = 2359/2854
[CV] END ............................................C=100.0; total time=45.1min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 139  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 140  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 141  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 142  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 143  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 144  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 145  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 146  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 147  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 148  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 149  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 150  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 151  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 152  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 153  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 154  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 155  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 156  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 157  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 158  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 159  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 160  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 161  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 162  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 163  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 164  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 165  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 126319866.022956
#nonzeros/#features = 2854/2854
[CV] END .........................................C=100000.0; total time=55.3min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 166  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 704664.754140
#nonzeros/#features = 2846/2854
[CV] END ...........................................C=1000.0; total time=55.7min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 167  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 168  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 169  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 170  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 6739904.794765
#nonzeros/#features = 2854/2854
[CV] END ..........................................C=10000.0; total time=57.2min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 171  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 172  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 173  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 174  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 175  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 176  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 177  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 178  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 179  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 180  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 181  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 141640.838451
#nonzeros/#features = 2469/2854
[CV] END ............................................C=100.0; total time=61.4min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 182  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 183  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 184  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 1262767.625715
#nonzeros/#features = 2851/2854
[CV] END ...........................................C=1000.0; total time=62.7min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

WARNING: reaching max number of inner iterations
iter 185  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 186  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 187  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 188  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 189  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 190  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 191  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 192  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 193  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 194  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 195  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 196  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 197  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 198  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 199  #CD cycles 1000
WARNING: reaching max number of inner iterations
iter 200  #CD cycles 1000
=========================
optimization finished, #iter = 200
WARNING: reaching max number of iterations
Objective value = 12292678.241247
#nonzeros/#features = 2853/2854
[CV] END ..........................................C=10000.0; total time=68.5min

/home/hixonbm/cssema415/src/.venv/lib/python3.11/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[LibLinear]iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   4  #CD cycles 1
iter   5  #CD cycles 3
iter   6  #CD cycles 1
iter   7  #CD cycles 8
iter   8  #CD cycles 1
iter   9  #CD cycles 17
iter  10  #CD cycles 1
iter  11  #CD cycles 68
iter  12  #CD cycles 1
=========================
optimization finished, #iter = 12
Objective value = 296.053268
#nonzeros/#features = 97/2854

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=LogisticRegression(l1_ratio=1, max_iter=200,
                                          solver='liblinear', verbose=2),
             n_jobs=-1,
             param_grid={'C': array([1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02,
       1.e+03, 1.e+04, 1.e+05])},
             verbose=2)

The model chose 97 nonzero features.

In [14]:
cv.best_params_

{'C': np.float64(0.1)}

The ideal C is 0.1 and ideal alpha is 10.

In [15]:
best_estimator = cv.best_estimator_

In [ ]:
weights = pd.DataFrame()
weights["Feature"] = X_poly_train.columns
weights["Weight"] = best_estimator.coef_[0]
weights = weights.sort_values(by="Weight", ascending = False)
display(weights.head(10))
display(weights.tail(10))

                                                Feature    Weight
1772  previous_10_games_team1_range_kast previous_10...  0.141591
1495  previous_10_games_team1_range_adr previous_10_...  0.114983
2470  previous_10_games_team2_range_deaths previous_...  0.105773
1193  previous_10_games_team1_range_assists previous...  0.097866
1267  previous_10_games_team1_min_assists previous_1...  0.096495
1082  previous_10_games_team1_std_assists previous_1...  0.092180
2145  previous_10_games_team1_min_kddiff previous_10...  0.090330
414   previous_10_games_team1_range_kills previous_1...  0.071848
1960  previous_10_games_team1_average_kddiff previou...  0.064902
2657  previous_10_games_team2_min_assists previous_1...  0.062628

                                                Feature    Weight
216   team2_previous_10_average_map_score previous_1... -0.062417
2169  previous_10_games_team1_median_kddiff previous... -0.065599
2161  previous_10_games_team1_median_kddiff previous... -0.080650
2069               previous_10_games_team1_max_kddiff^2 -0.081494
624   previous_10_games_team1_median_kills previous_... -0.091414
164   team2_previous_10_average_map_score previous_1... -0.110048
2802  previous_10_games_team2_range_kast previous_10... -0.117023
2841  previous_10_games_team2_range_kddiff previous_... -0.119625
1137  previous_10_games_team1_std_assists previous_1... -0.153820
1461  previous_10_games_team1_std_adr previous_10_ga... -0.209154

In [20]:
with pd.option_context('display.max_colwidth', None):
    print(weights.Feature.head(1))
    print(weights.Feature.tail(3))

1772    previous_10_games_team1_range_kast previous_10_games_team1_average_kddiff
Name: Feature, dtype: object
2841      previous_10_games_team2_range_kddiff previous_10_games_team2_min_kddiff
1137    previous_10_games_team1_std_assists previous_10_games_team2_median_kddiff
1461           previous_10_games_team1_std_adr previous_10_games_team2_range_kast
Name: Feature, dtype: object

Looks like the 4 most important features according to the model, all being interaction terms, are team 2 range kddiff and team 2 min kddiff; team 1 std assists and team 2 median kddiff; team 1 std adr and team 2 range kast; and team 1's kast range and team 1's average kddiff.

In [21]:
best_estimator.score(X_poly_train, y_train)

0.6042418772563177

In [22]:
best_estimator.score(X_poly_test, y_test)

0.5573622402890696

It does much worse than the original L1 regularized feature set. I think the reason these features do well in the train test and validation tests is because at the time training data is collected and analyzed, certain metas and tactics are likely more meaningful at the time; however, once playstyles evolve at later record dates, certain other stats become more important which the already trained model does not know. The temporal nature of this problem seems to be more of a challenge than anticipated.